### PR TITLE
Fixes #55 - stop server should not be terminating always

### LINKED ISSUE #55: Stop server always terminates server
```
       if ((!forced && serverState === ServerState.STARTED)
            || (forced && (serverState === ServerState.STARTING
                            || serverState === ServerState.STOPPING))) {
            const client: RSPClient = this.explorer.getClientByRSP(context.rsp);
            if (!client) {
                return Promise.reject('Failed to contact the RSP server.');
            }
const status = await client.getOutgoingHandler().stopServerAsync({ id: context.server.id, force: true `});

```
You can see here that 'force' is always set to true.  Stopping a normal server is now terminating it. Bad news.

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

### CODE REVIEW

File: src/extensionApi.ts [hunk 1]
```diff
@@ -149,10 +149,12 @@ export class CommandHandler {
...
         if (context === undefined) {
             const rsp = await this.selectRSP('Select RSP provider you want to retrieve servers');
-            if (!rsp || !rsp.id) return null;
+            if (!rsp || !rsp.id) 
+                return Promise.reject("No RSP chosen");
             const serverFilter = server => server.state === ServerState.STARTED;
             const serverId = await this.selectServer(rsp.id, 'Select server to stop.', serverFilter);
-            if (!serverId) return null;
+            if (!serverId) 
+                return Promise.reject("No Server chosen");
```
Comment (lstocchi) [inline src/extensionApi.ts]: In this case we don't need to show any error message because the user clicked 'esc' instead of choosing a server. So we just need to stop the workflow.

File: src/extensionApi.ts [hunk 2]
```diff
@@ -149,10 +149,12 @@ export class CommandHandler {
     public async stopServer(forced: boolean, context?: ServerStateNode): Promise<Protocol.Status> {
         if (context === undefined) {
             const rsp = await this.selectRSP('Select RSP provider you want to retrieve servers');
-            if (!rsp || !rsp.id) return null;
+            if (!rsp || !rsp.id) 
+                return Promise.reject("No RSP chosen");
```
Comment (lstocchi) [inline src/extensionApi.ts]: In this case we don't need to show any error message because the user clicked 'esc' instead of choosing a rsp provider. So we just need to stop the workflow.

File: src/extensionApi.ts (hunk 1 above)
Comment (adietish) [reply src/extensionApi.ts]: @lstocchi well catched, we still have a few of those where aborting prompts would show an error.
